apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-difflouvain
  name: kafkadifflouvain1
spec:
  ports:
    - name: client
      port: 9092
      protocol: TCP
  selector:
    app: kafka-difflouvain
  type: LoadBalancer
