apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper-kafka
  template:
    metadata:
      labels:
        app: zookeeper-kafka
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_ID
              value: '1'
            - name: ZOOKEEPER_SERVER_1
              value: zookeeperkafka1
          image: digitalwonderland/zookeeper
          name: zookeeperkafka1
          ports:
            - containerPort: 2081
