apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-kafka
  name: zookeeperkafka1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-kafka
  type: NodePort
